Feature/auth
darsal03/PROJECT pull request #13
Opened 2021-10-29 16:43 UTC by darsal03

main task was done ,however i'm not sure about fastest-validator implementation

2021-10-30 18:05 UTC, ggogobera requested changes
იდეა სწორად გაქვს გაგებული, კარგად არის გაკეთებული

მცირე ცვლილებებს შევიტანდი და ცვლადების სახელები გამოასწორე და გაუფრთხილდი აუცილებლად

2021-10-30 18:05 UTC, ggogobera commented on server/src/controllers/users.js
> +    const messages = await validateUser({ username, email, password })
validationState უფრო კარგი სახელია. მესიჯები საერთოდ არ ასოცირდება ერორებთან

2021-10-30 18:05 UTC, ggogobera commented on server/src/controllers/users.js
> +      return res.status(400).json({ msg: messages })
როცა ერორის სტატუს კოდს აბრუნებ, errors უნდა დაარქვა ფროფერთის, უფრო კონვენციურია

2021-10-30 18:05 UTC, ggogobera commented on server/src/middlewares/auth.js
> +import { Users } from '../models/User.js'
ლაინ ბრეიქი ამ ლაინის შემდეგ. ცოტა ესთეტიურ მხარეზეც იფიქრე რა, რა მიაყარე ერთმანეთს :დდ

2021-10-30 18:05 UTC, ggogobera commented on server/src/middlewares/auth.js
> +      msg: 'authentication failed',
error

2021-10-30 18:05 UTC, ggogobera commented on server/src/middlewares/forbidFor.js
> +      msg: 'forbidden',
error

2021-10-30 18:05 UTC, ggogobera commented on server/src/utils/validateUser.js
> +  const validate = await check({ username, email, password })
validate ზმნა არის და არა არსებითი სახელი. ფუნქცია ხომ არ არის validate? რატომ გეშლება ესეთი რაღაცები? ცვლადების სახელებს მოუფრთხილდი

if (validate) არ იკითხება თან. ჩემი აზრით არ უნდა მჭირდებოდეს ასეთი რაღაცის თქმა

2021-10-30 18:05 UTC, ggogobera commented on server/src/utils/validateUser.js
> +  }
```js
{
  isValid: boolean,
  errorMessages: validationState.map(err => err.message)
}
```
ასეთ შეიფს დავაბრუნებდი

2021-10-30 18:06 UTC, ggogobera commented
რაღა დაგიმალო და ძალიან ბევრს აკომიტებ.

ამ ბრენჩში სამჯერ დავაკომიტებდი მაგალითად, ერთი როლები, მეორე auth და მესამე validation

2021-10-31 13:37 UTC, darsal03 commented on server/src/middlewares/auth.js
> +      msg: 'authentication failed',
სადაც msg მაქ ჩავასწორებ errorit

2021-10-31 20:48 UTC, ggogobera requested changes
არასწორად გაქვს გაგებული ჩემი ნათქვამი.

როცა ვალიდაციას აკეთებ იუზერისას და ბევრ შემთხვევაში აბრუნებ 400 სტატუს კოდს, როგორ გაიგოს კლიენტმა რა იყო მიზეზი?

if userFound error: "user already found"

მე მესიჯში ის კი არ ვიგულისხმე რომ სტრინგი არ დაუბრუნომეთქი, ზოგადად, error ყველაფერი შეიძლება იყოს, აუცილებელი არაა მხოლოდ მესიჯიმეთქი

createUser ფუნქცია ჩასასწორებელია

2021-10-31 20:52 UTC, ggogobera commented
ანუ, რომც ეგრე გაგეგო, უნდა გაგეკრიტიკებინე.

წარმოიდგინე გაქვს 3 ქეისი როცა 400-ს აბრუნებ, ერთი იუზერნეიმის არასწორიას გამო, მეორე რაღაცა არასწორია და მესამე კიდე რაღაცა არასწორია... არაფერი რომ არ დაუბრუნო, ვერ გაიგებს ტიპი რა დააშავა

2021-11-01 09:00 UTC, merged