Feature/role based restriction
darsal03/PROJECT pull request #15
Opened 2021-11-01 18:20 UTC by darsal03

2021-11-02 10:59 UTC, ggogobera requested changes

2021-11-02 10:59 UTC, ggogobera commented on server/src/controllers/meals.js
> +      return res.status(400).json({
403 status code

2021-11-02 10:59 UTC, ggogobera commented on server/src/controllers/meals.js
> +    if (userId != req.user._id && (req.user.role == 'user') | (req.user.role == 'moderator')) {
```js
!=
==
==
```

C++-ში წერ? :დ

2021-11-02 10:59 UTC, ggogobera commented on server/src/controllers/users.js
> +    if (id != req.user._id && req.user.role == 'user') {
რა არის ეს non-strict უტოლობები?

2021-11-02 10:59 UTC, ggogobera commented on server/src/controllers/users.js
> +      return res.status(400).json({
403

2021-11-02 10:59 UTC, ggogobera commented on server/src/controllers/users.js
> +      return res.status(400).json({ erro: 'email is already taken ' })
erro?

2021-11-02 10:59 UTC, ggogobera commented
DELETE, PUT მეთოდებსაც უნდათ იგივე შეზღუდვები, თუ თავისი არაა არ უნდა წაშალოს ან შეცვალოს და თუ ადმინი არაა

2021-11-03 11:46 UTC, ggogobera requested changes

2021-11-03 11:46 UTC, ggogobera commented on server/src/controllers/meals.js
> +      (req.user.role === 'user') | (req.user.role === 'moderator')
| ?

2021-11-03 11:46 UTC, ggogobera commented on server/src/controllers/meals.js
> +      (req.user.role === 'user') | (req.user.role === 'moderator')
admin?

```js
userId !== req.user._id.toString() && [Roles.User, Roles.Moderator].includes(req.user.role)
```

მე უნდა გიწერდე ბიჭო if სთეითმენთებს? Roles ენამი რომ შექმენი, რატომ არ იყენებ?

2021-11-03 11:46 UTC, ggogobera commented on server/src/controllers/meals.js
> +    if (foundMeal.userId.toString() !== req.user._id.toString() && req.user.role === 'user') {
არც მოდერატორს უნდა შეეძლოს წაშლა. იგივე ქონდიშენი უნდა დაწერო რაც getMeals-ში

2021-11-03 11:46 UTC, ggogobera commented on server/src/controllers/meals.js
> +    if (foundMeal.userId.toString() !== req.user._id.toString() && req.user.role === 'user') {
აქაც იგივე სთეითმენთი რაც ზემოთ

2021-11-03 11:46 UTC, ggogobera commented on server/src/controllers/meals.js
> +    if (foundMeal.userId.toString() !== req.user._id.toString() && req.user.role === 'user') {
აქაც. მოდერატორს მხოლოდ იუზერების და თავისი საჭმლის შეცვლა შეუძლია

2021-11-03 13:45 UTC, darsal03 commented on server/src/controllers/meals.js
> +      (req.user.role === 'user') | (req.user.role === 'moderator')
"admin?" რატომ გიწერია ვერ ვხვდები

2021-11-03 19:55 UTC, ggogobera approved these changes

2021-11-03 19:57 UTC, merged