Feature/register form
darsal03/PROJECT pull request #21
Opened 2021-11-21 13:57 UTC by darsal03

გოგა dotenv-იც დავაყენე ,არ გეწერა,მაგრამ ხომ დაგვჭირდება?

2021-11-22 10:00 UTC, ggogobera requested changes

2021-11-22 10:00 UTC, ggogobera commented on client/src/containers/Login.jsx
> +      <button type="button" onClick={setView}>
აქ შეცდომა გაქვს, ერორს გამოიწვევს.

setView ფუნქცია სტეიტში სეტავს გადაცემულ ველიუს. view-ს სტეიტმა უნდა მიიღოს სულ 2 ნაირი მნიშვნელობა, რეგისტრაციის ან ლოგინი ენამი.

ახლა setView-ს გადაეწოდება event. () => setView(VIEWS.Register) ასე უნდა გქონდეს

2021-11-22 10:01 UTC, ggogobera commented on client/src/containers/Login.jsx
> +        <LoginLinkButton type="button" onClick={setView}>
აქაც გაქვს ის ბაგი, რაც ბოლო კომენტარსი დაგიწერე

2021-11-24 19:58 UTC, ggogobera requested changes

2021-11-24 19:58 UTC, ggogobera commented on client/src/api/users.js
> +  fetch(`${apiUrl}/users/` || 'http://localhost:8080/api/users/', {
'http://localhost:8080/api/users/' ეს რა საჭიროა, ყოველთვის გექნება დასეტილი

2021-11-24 19:58 UTC, ggogobera commented on client/src/api/users.js
> +    body: JSON.stringify(form),
პირდაპირ არასდროს გადასცე body-ს. პარამეტრის დესტრუქტურიზაცია გააკეთე და მხოლოდ ის გადაეცი ბადის, რასაც აპი გთხოვს

2021-11-24 19:58 UTC, ggogobera commented on client/src/containers/Login.jsx
> +
ნუ ყოფ ადგილებს ზედმეტად, რა საჭიროა

2021-11-24 19:58 UTC, ggogobera commented on client/src/containers/Login.jsx
> +  maxWi: '600px',
60rem

2021-11-24 19:58 UTC, ggogobera commented on client/src/containers/Login.jsx
> +  boxShadow: 'rgba(0, 0, 0, 0.35) 0px 5px 15px;',
```js
boxShadow: '0 0.5rem 1.5rem rgba(0, 0, 0, 0.35)'
```

p.s. წერტილ მძიმე არ სჭირდება

2021-11-24 19:58 UTC, ggogobera commented on client/src/hooks/useRegistration.jsx
> +export default useRegistration
აი ამ ჰუკის შექმნის დროს გაგიჩნდებოდა კითხვა რა საჭიროა და ძალიანაც მნიშვნელოვანი კითხვაა.

როდესაც ტესტებს წერ, ხშირად გიწევს რაღაცების და mock-ვა. mocking არის მეთოდი, როცა იუნიტ ტესტინგის დროს არსებულ ფუნქციონალს ანაცვლებ dummy ფუნქციონალით, რადგან კონკრეტულ რაღაცას ცალკე თავისი ტესტები ექნება და ცალკე სადაც გამოიყენება იქ დატესტვა აღარ უნდა იყოს საჭირო.

კომპონენტში როცა 1-ზე მეტი useMutation გაქვს, ვერ დამოქავ. მოქის დროს იმპლემენტაცია უნდა მიუთითო, რითაც ჩაანაცვლებ რეალურ ფუნქციონალს. რომ გინდოდეს რეგისსტრაციის useMutation-ს დამოქვა, სხვაც დაიმოქება.

ამიტომ ქმნი ცალკე ჰუკს, რომელიც უნიკალური იქნება ყოველთვის და დამოქვა მარტივი იქნება.

example: https://jestjs.io/docs/mock-functions

2021-11-25 14:08 UTC, ggogobera approved these changes

2021-11-25 14:08 UTC, ggogobera commented on client/src/api/users.js
> +  const { username, email, password } = form
პარამეტრშივე გექნა არ ჯობდა?

2021-11-25 14:50 UTC, darsal03 commented on client/src/api/users.js
> +  const { username, email, password } = form
არადა გავიფიქრე რაღაცა ნიტოა თქო,ჩავასწორებ

2021-11-25 14:54 UTC, merged