Feature/login form
darsal03/PROJECT pull request #23
Opened 2021-11-27 22:00 UTC by darsal03

2021-12-05 13:33 UTC, ggogobera requested changes
ზედა კომენტარი და Route-ბიც დაფიქსე. ეგ სტრუქტურა აღარ გამოდგება ამ შემთხვევაში

2021-12-05 13:33 UTC, ggogobera commented on client/src/containers/Home.jsx
> +  return <div>{user ? <Dashboard username={user.username} /> : 'not authed'}</div>
ეს არ უნდა გჭირდებოდეს საერთოდ.
ბლოგში ხომ ეწერა, AuthenticatedApp და UnAuthenticatedApp კომპონენტებს არენდერებ App-ში, auth-ს მიხედვით.

ასეთ პატარა აპლიკაციაში ყველ აკომპონენტში ამის მოწმება არაა კარგი იდეა

2021-12-06 20:03 UTC, darsal03 commented on client/src/containers/Content.jsx
> +      <button onClick={onClick}>MEALS</button>
ეს დააიგნორე რა, რაღაცას ვტესტავდი და დამავიწყდა ამოშლა, ეხლა უკვე ამოშლილი მაქ

2021-12-06 20:14 UTC, darsal03 commented on client/src/index.jsx
> +          <Route path="/" element={<App />}></Route>
ეხლა აპლიკაცია აჩვენებს ლოგინს, რადგან UnAuthedApps ევალება ლოგინ-რეგისტერის კომპონენტების რენდერი,ლოგინის მერე "home" ფეიჯზე ვუშვებ,ანუ AuthedApp-ს ვარენდერებ.                                       
იმას რა თქმა უნდა ვხვდები , რომ ეს სტუქტურა არ დაჰენდლავს ყველაფერს ,მარა ამ კონკრეტულ ტასკისთვის მუშაობს.   
 ( i'm lowkey lost here ngl)

2021-12-11 12:52 UTC, ggogobera approved these changes
ვაეფრუვებ, მაგრამ კომენტარი შეამოწმე და დააექსპერიმენტე. მომდევნო issues-ს გავხსნი მალე

2021-12-11 12:52 UTC, ggogobera commented on client/src/index.jsx
> +          <Route path="/" element={<App />}></Route>
აქ Routes-ს ქონას აზრი აღარ აქვს. როუტები უკვე აღწერილი გექნება AuthedApp-ში ან UnauthedApp-ში.

- AuthedApp
```jsx
<Routes>
    <Route path='/' element={<Meals />} />
    <Route path='/profile' element={<Profile />} /> in future
    <Route path='*' element={<NotFound />} />
</Routes>
```

- UnAuthedApp
```jsx
<Routes>
    <Route path='/auth' element={<Auth />} />
    <Route path='*' element={<ComponentWhichRedirectsToAuth />} />
</Routes>
```

2021-12-11 13:26 UTC, merged