Feature/user management
darsal03/PROJECT pull request #34
Opened 2022-02-14 18:05 UTC by darsal03

2022-02-14 21:10 UTC, ggogobera requested changes

2022-02-14 21:10 UTC, ggogobera commented on client/src/api/users.js
> +    .then((data) => data.foundUsers)
რა საჭიროა data.founders? პირდაპირ რომ foundUsers-ს აბრუნებდეს?

2022-02-14 21:10 UTC, ggogobera commented on client/src/components/Header.jsx
> +            <button onClick={onNavigate}>Users</button>
ეს button-ს მაგივრად a უნდა იყოს, სემანტიკურად უფრო სწორია.

onNavigate-ც აღარ დაგწირდებოდა. ჩვეულებრივი url არის — /users

ეს ჩემი user.role აქ არ უნდა იყოს, უნდა იყოს Users გვერდზე. წინააღმდეგ შემთხვევაში ჩვეულებრივი იუზერიც შევიდოდა პირდაპირ ლინკით.

2022-02-14 21:10 UTC, ggogobera commented on client/src/components/Header.jsx
> +    <StyledHeader auth={user ? true : false}>
```js
auth={Boolean(user)}
```
ან
```js
auth={!!user}
```

as u wish

2022-02-14 21:10 UTC, ggogobera commented on client/src/containers/Content.jsx
> +        {(user.role === 'admin' || user.role === 'moderator') && (
ditto

2022-02-14 21:10 UTC, ggogobera commented on client/src/containers/UserEdit.jsx
> +const ProfilePageWrapper = styled('div', {
ეს copy paste არის გასაგებია, მაგრამ დააკვირდი დეტალებს

2022-02-14 21:10 UTC, ggogobera commented on client/src/containers/UsersPage.jsx
> +  const handleDelete = (event, id = selectedUser.id) => {
მეორე პარამეტრის აღწერა ამ ფუნქციასი არასწორია. onClick მეორე პარამეტრს არ გადასცემს ფუნქციას.

პირდაპირ onUserDelete(selectedUser.id)

2022-02-14 21:10 UTC, ggogobera commented on client/src/containers/UsersPage.jsx
> +  const handleModal = (event, id = user.id, username = user.username) => {
ditto same as above

რატომ მოგაფიქრდა ასეთი რაღაც?

handleModal -> handleDelete

2022-02-14 21:10 UTC, ggogobera commented on client/src/containers/UsersPage.jsx
> +  const handleNavigate = (event, id = user.id, username = user.username) => {
ditto

handleEdit

2022-02-14 21:10 UTC, ggogobera commented on client/src/containers/UsersPage.jsx
> +}
ყველაფერი ერთ ფაილში რატომ გაქვს? არ სჯობს დაყო პატარ პატარა component ფაილებად?

2022-02-14 21:10 UTC, ggogobera commented on client/src/hooks/use-delete-user.js
> +      queryClient.invalidateQueries({ queryKey: 'users' })
ამას პირდაპირ queryKey-ს არ გადაეწოდება ობიექტის მაგივრად?

2022-02-14 21:10 UTC, ggogobera commented on client/src/hooks/use-edit-user.js
> +      queryClient.invalidateQueries({ queryKey: ['user'] })
ditto

2022-02-15 14:44 UTC, darsal03 commented on client/src/hooks/use-delete-user.js
> +      queryClient.invalidateQueries({ queryKey: 'users' })
კი ,overkill-ივით გამოდის მე როგორც მაქ , ამოვშლი

2022-02-15 17:36 UTC, darsal03 commented on client/src/components/Header.jsx
> +            <button onClick={onNavigate}>Users</button>
--> "ეს ჩემი user.role აქ არ უნდა იყოს, უნდა იყოს Users გვერდზე. წინააღმდეგ შემთხვევაში ჩვეულებრივი იუზერიც შევიდოდა პირდაპირ ლინკით."

გოგა ვერ მივუხვდი ამ კომენტარს, და რაუტებზეც რომ გიწერია იგივე ,მაგასაც.

2022-02-15 21:50 UTC, ggogobera commented on client/src/components/Header.jsx
> +            <button onClick={onNavigate}>Users</button>
ჩვეულებრივი მომხმარებელი `/users` მისამართზე რომ შევიდეს გვერდი ჩაიტვირთება თუ არა?

ღილაკის მაგივრად ლინკი უნდა იყოს ეს

2022-02-17 10:09 UTC, ggogobera approved these changes
კარგია, კომიტები ძალიან მომწონს.

პატარ კომენტარი დავტოვე მაგრამ ვაეფრუვებ

2022-02-17 10:09 UTC, ggogobera commented on client/src/api/users.js
> +    .then((data) => data)
არა ეს არ იგულისხმია. თვითონ data-ში არ უნდა იყოს foundUsers ფროფერთი. data პირდაპირ foundUsers უნდა იყოს

2022-02-17 10:40 UTC, merged